export default {
	IMAGE: "image",
	SPRITE: "sprite",
	TILING_SPRITE: "tilingSprite",
	ANIMATED_SPRITE: "animatedSprite",
	TEXT: "text",
	CONTAINER: "container",
	GRAPHICS: "graphics",
	PARTICLE_EMITTER: "particleEmitter",
	SPINE: "spine",
	NINESLICE: "nineslice",
	SCENE: "scene",
	STAGE: "stage",
	VIEWPORT: "viewport",
	RECTANGLE: "rectangle",
	CIRCLE: "circle",
};
